site_name: SystemThinking.sk
theme:
  name: material
  language: sk

plugins:
  - search
  - awesome-pages
  - i18n:
      default_language: sk
      languages:
        sk: Slovensky
        en: English

nav:
  - Slovensky:
      - Úvod: sk/index.md
  - English:
      - Home: en/index.md
